name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python 3.10 Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Install mypy
        run: pip install mypy==0.991
      - name: Run mypy
        run: mypy .
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python 3.10 Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Install flake8
        run: pip install flake8==6.0.0 flake8-import-order==0.18.2
      - name: Run flake8
        run: flake8 .
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python 3.10 Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Install bandit
        run: pip install bandit==1.7.4
      - name: Run bandit
        run: bandit -r .
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python 3.10 Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Install isort
        run: pip install isort==5.12.0
      - name: Run isort
        run: isort --check-only --diff .
